let spuxFinderOpen=false,spuxFinderIndex=0,spuxFinderLastFocus=null,spuxDiffOnly=false;
function spuxIndustryFact(x){return firstFact(x,'industry')}
function spuxIndustryText(x){let f=spuxIndustryFact(x),v=f?.value;if(!f)return '';if(v&&typeof v==='object')return [v.description,v.code].filter(Boolean).join(' · ')||fmt(v);return fmt(v)}
function spuxSearchText(x){return norm([x.name,x.org,x.municipality,spuxIndustryText(x)].filter(Boolean).join(' '))}
function spuxAvailabilityLabel(value){return String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}
function spuxCoverage(x){return AREAS.filter(([key])=>x.areaAvailability?.[key]).length}
function spuxAreaState(x,key){let fs=x.areas?.[key]||[];if(fs.some(f=>f.availability==='available'))return {label:'Found',cls:'found'};let state=fs.map(f=>f.availability).find(Boolean);if(state)return {label:spuxAvailabilityLabel(state),cls:String(state).replaceAll('_','-')};return {label:'No record',cls:'no-record'}}
function spuxCopy(text){if(!text)return;let done=()=>toast('Copied to clipboard');if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(done).catch(()=>spuxCopyFallback(text))}else spuxCopyFallback(text)}
function spuxCopyFallback(text){let t=document.createElement('textarea');t.value=text;t.setAttribute('readonly','');t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();try{document.execCommand('copy');toast('Copied to clipboard')}catch(_){toast('Copy unavailable')}t.remove()}
function spuxSelectCompany(org){let x=companyFor(org);if(!x)return;selected=x.org;spuxCloseFinder();setMode('explore');renderList();renderProfile();renderAskIdle();renderTimelineOptions();requestAnimationFrame(()=>$('#profile')?.scrollIntoView({behavior:'smooth',block:'start'}))}
function spuxFinderRows(query){let q=norm(query),rows=DATA.filter(x=>!q||spuxSearchText(x).includes(q));rows.sort((a,b)=>spuxCoverage(b)-spuxCoverage(a)||String(a.name).localeCompare(String(b.name)));return rows.slice(0,10)}
function spuxRenderFinder(){let input=$('#companyFinderInput'),box=$('#companyFinderResults');if(!input||!box)return;let rows=spuxFinderRows(input.value);spuxFinderIndex=Math.max(0,Math.min(spuxFinderIndex,Math.max(0,rows.length-1)));if(!rows.length){box.innerHTML='<div class="finder-empty"><strong>No matching companies</strong><div>Try a company name, organisation number, industry or place.</div></div>';return}box.innerHTML=rows.map((x,i)=>`<button class="finder-result ${i===spuxFinderIndex?'active':''}" type="button" data-org="${esc(x.org)}"><span><strong>${esc(x.name)}</strong><small>${esc(x.org)}${x.municipality?` · ${esc(x.municipality)}`:''}</small>${spuxIndustryText(x)?`<small class="industry">${esc(spuxIndustryText(x))}</small>`:''}</span><span class="finder-coverage">${spuxCoverage(x)}/5 areas</span></button>`).join('');$$('#companyFinderResults .finder-result').forEach(b=>b.onclick=()=>spuxSelectCompany(b.dataset.org));let active=$('#companyFinderResults .finder-result.active');active?.scrollIntoView({block:'nearest'})}
function spuxOpenFinder(){let modal=$('#companyFinder');if(!modal)return;spuxFinderLastFocus=document.activeElement;spuxFinderOpen=true;spuxFinderIndex=0;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';let input=$('#companyFinderInput');input.value='';spuxRenderFinder();requestAnimationFrame(()=>input.focus())}
function spuxCloseFinder(){let modal=$('#companyFinder');if(!modal||!spuxFinderOpen)return;spuxFinderOpen=false;modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow='';if(spuxFinderLastFocus?.focus)spuxFinderLastFocus.focus()}
function spuxInstallFinder(){if($('#companyFinder'))return;let top=$('.top-inner'),brand=$('.brand'),hero=$('.hero'),heroTitle=$('.hero h1');if(top&&brand){brand.insertAdjacentHTML('afterend','<button id="globalFinderTrigger" class="global-finder-trigger" type="button" aria-haspopup="dialog" aria-controls="companyFinder" title="Search companies · Ctrl or Command K"><span class="find-icon" aria-hidden="true">⌕</span><span class="find-label">Search companies</span><kbd>⌘K</kbd></button>')}if(hero&&heroTitle){heroTitle.insertAdjacentHTML('afterend','<button id="heroFinderTrigger" class="global-finder-trigger hero-find" type="button" aria-haspopup="dialog" aria-controls="companyFinder"><span class="find-icon" aria-hidden="true">⌕</span><span class="find-label">Search company, organisation number, industry or place</span><kbd>⌘K</kbd></button>')}let modal=document.createElement('div');modal.id='companyFinder';modal.className='company-finder';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','companyFinderTitle');modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="finder-panel"><div class="finder-head"><div class="finder-input-wrap"><span class="find-icon" aria-hidden="true">⌕</span><label class="sr-only" id="companyFinderTitle" for="companyFinderInput">Find a company</label><input id="companyFinderInput" type="search" autocomplete="off" placeholder="Search company, organisation number, industry or place"><button id="companyFinderClose" class="finder-close" type="button" aria-label="Close company finder">×</button></div><div class="finder-hint">Use ↑ ↓ to move · Enter to open · Esc to close</div></div><div id="companyFinderResults" class="finder-results" role="listbox" aria-label="Company search results"></div></div>';document.body.appendChild(modal);$('#globalFinderTrigger')?.addEventListener('click',spuxOpenFinder);$('#heroFinderTrigger')?.addEventListener('click',spuxOpenFinder);$('#companyFinderClose').onclick=spuxCloseFinder;modal.addEventListener('mousedown',e=>{if(e.target===modal)spuxCloseFinder()});$('#companyFinderInput').addEventListener('input',()=>{spuxFinderIndex=0;spuxRenderFinder()});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();spuxFinderOpen?spuxCloseFinder():spuxOpenFinder();return}if(!spuxFinderOpen)return;if(e.key==='Escape'){e.preventDefault();spuxCloseFinder();return}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();let rows=spuxFinderRows($('#companyFinderInput').value);if(!rows.length)return;spuxFinderIndex=(spuxFinderIndex+(e.key==='ArrowDown'?1:-1)+rows.length)%rows.length;spuxRenderFinder();return}if(e.key==='Enter'&&document.activeElement===$('#companyFinderInput')){e.preventDefault();let rows=spuxFinderRows($('#companyFinderInput').value);if(rows[spuxFinderIndex])spuxSelectCompany(rows[spuxFinderIndex].org)}})}
function spuxEnhanceDirectory(){let list=$('#list');if(!list)return;$$('.company-row').forEach(row=>{let x=companyFor(row.dataset.org);if(!x)return;if(spuxIndustryText(x)&&!row.querySelector('.row-industry')){let meta=row.querySelector('small');meta?.insertAdjacentHTML('afterend',`<small class="row-industry">${esc(spuxIndustryText(x))}</small>`)}if(!row.querySelector('.row-coverage'))row.insertAdjacentHTML('beforeend',`<span class="row-coverage">${spuxCoverage(x)}/5</span>`)})}
function spuxEnhanceProfile(){let x=selectedCompany(),profile=$('#profile');if(!x||!profile)return;let actions=profile.querySelector('.profile-actions');if(actions){let verify=document.createElement('button');verify.type='button';verify.className='btn verify-all';verify.textContent='Verify all evidence';verify.onclick=()=>openEvidence(uniqEvidence(evidenceRows(x)),`All evidence · ${x.name}`);let compare=document.createElement('button');compare.type='button';compare.className='btn';compare.textContent='Compare this company';compare.onclick=()=>{compareA=x.org;if(compareB===x.org)compareB=DATA.find(c=>c.org!==x.org)?.org||x.org;setMode('compare')};actions.append(verify,compare)}let head=profile.querySelector('.profile-head');if(head){let strip=document.createElement('div');strip.className='verification-strip';strip.setAttribute('aria-label','Evidence coverage by data area');let labels={company_record:'Company',financials:'Financials',people_and_locations:'People',company_website:'Website',hiring_and_public_activity:'Activity'};strip.innerHTML=AREAS.map(([key])=>{let s=spuxAreaState(x,key);return `<button class="verification-item ${esc(s.cls)}" type="button" data-target="${esc(key)}"><strong>${esc(labels[key]||key)}</strong><span>${esc(s.label)}</span></button>`}).join('');head.insertAdjacentElement('afterend',strip);$$('.verification-item').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'}))}}
function spuxCompareMeaning(cell){if(!cell)return '';let clone=cell.cloneNode(true);clone.querySelectorAll('button,.compare-sources,.sub,.meta').forEach(n=>n.remove());return norm(clone.textContent.replace(/\s+/g,' ').trim())}
function spuxApplyCompareFilter(){let rows=$$('#comparison .compare-row'),diff=0;rows.forEach(r=>{let cells=r.querySelectorAll('.compare-cell'),isDifferent=cells.length===2&&spuxCompareMeaning(cells[0])!==spuxCompareMeaning(cells[1]);r.classList.toggle('is-different',isDifferent);if(isDifferent)diff++;r.hidden=spuxDiffOnly&&!isDifferent});let meta=$('#compareDiffMeta');if(meta)meta.textContent=spuxDiffOnly?`${diff} differing field${diff===1?'':'s'} shown`:`${diff} of ${rows.length} fields differ`;let btn=$('#compareDiffToggle');if(btn){btn.setAttribute('aria-pressed',spuxDiffOnly?'true':'false');btn.textContent=spuxDiffOnly?'Showing differences':'Differences only'}}
function spuxInstallCompareTools(){let comparison=$('#comparison');if(!comparison||$('#compareDiffToggle'))return;let tools=document.createElement('div');tools.className='compare-tools';tools.innerHTML='<button id="compareDiffToggle" class="compare-diff-toggle" type="button" aria-pressed="false">Differences only</button><span id="compareDiffMeta" class="compare-diff-meta" aria-live="polite"></span>';comparison.insertAdjacentElement('beforebegin',tools);$('#compareDiffToggle').onclick=()=>{spuxDiffOnly=!spuxDiffOnly;spuxApplyCompareFilter()};spuxApplyCompareFilter()}
function spuxEnhanceEvidence(rows){let drawer=$('#evidenceDrawer'),body=$('#drawerBody');if(!drawer||!body)return;drawer.querySelector('.evidence-toolbar')?.remove();let ev=Array.isArray(rows)?rows:[],dates=ev.map(e=>e.retrievedAt).filter(Boolean).sort(),newest=dates.at(-1);let toolbar=document.createElement('div');toolbar.className='evidence-toolbar';toolbar.innerHTML=`<strong>${ev.length} evidence record${ev.length===1?'':'s'}</strong><span>${newest?`Latest retrieval ${esc(String(newest).slice(0,10))}`:'Retrieval date not reported'}</span>`;body.insertAdjacentElement('beforebegin',toolbar);$$('#drawerBody .evidence-card').forEach((card,i)=>{let e=ev[i]||{},link=card.querySelector('a[href]');if(e.url){let host='source';try{host=new URL(e.url).hostname.replace(/^www\./,'')}catch(_){}let chip=document.createElement('span');chip.className='evidence-host';chip.textContent=host;card.querySelector('.ev-class')?.insertAdjacentElement('afterend',chip);if(link){let copy=document.createElement('button');copy.type='button';copy.className='copy-source';copy.textContent='Copy link';copy.onclick=()=>spuxCopy(e.url);link.insertAdjacentElement('afterend',copy)}}})}
const spuxBaseRenderList=renderList;renderList=function(){spuxBaseRenderList();spuxEnhanceDirectory()};
const spuxBaseRenderProfile=renderProfile;renderProfile=function(){spuxBaseRenderProfile();spuxEnhanceProfile()};
const spuxBaseRenderCompare=renderCompare;renderCompare=function(){spuxBaseRenderCompare();spuxInstallCompareTools();spuxApplyCompareFilter()};
const spuxBaseOpenEvidence=openEvidence;openEvidence=function(ev,title='Evidence'){spuxBaseOpenEvidence(ev,title);spuxEnhanceEvidence(ev)};
spuxInstallFinder();spuxEnhanceDirectory();spuxEnhanceProfile();spuxInstallCompareTools();spuxApplyCompareFilter();
