const spCareersSurfaceLabel='Careers surface found.'
const spCareersOnlyBoundary='A verified company-owned careers page is published, but the current evidence does not establish an active vacancy.'
function spCareersFacts(x){return facts(x,'careers_page')}
function spHiringIntentFacts(x){return facts(x,'hiring_intent')}
function spJobFacts(x){return facts(x,'job_posting')}
function spCareersUrl(f){let v=f?.value;if(v&&typeof v==='object')return v.url||v.href||'';return typeof v==='string'&&/^https?:\/\//i.test(v)?v:''}
const spCareersBaseFilterPass=filterPass;
filterPass=function(x){if(activeFilter==='careers')return spCareersFacts(x).length>0||spHiringIntentFacts(x).length>0||spJobFacts(x).length>0;return spCareersBaseFilterPass(x)};
function spCareersInstallFilter(){let filters=$('#filters');if(!filters||filters.querySelector('[data-filter="careers"]'))return;let b=document.createElement('button');b.className='filter';b.dataset.filter='careers';b.type='button';b.textContent='Hiring';b.onclick=()=>{activeFilter='careers';$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderList()};let changed=filters.querySelector('[data-filter="changes"]');filters.insertBefore(b,changed||null)}
function spCareersEnhanceList(){ $('.company-row').forEach(row=>{let x=companyFor(row.dataset.org),badges=row.querySelector('.row-badges');if(!x||!badges)return;let careers=spCareersFacts(x),intent=spHiringIntentFacts(x),jobs=spJobFacts(x);if(jobs.length&&!badges.querySelector('.jobs-badge'))badges.insertAdjacentHTML('beforeend','<span class="dot-badge on jobs-badge">jobs</span>');else if(intent.length&&!badges.querySelector('.hiring-intent-badge'))badges.insertAdjacentHTML('beforeend','<span class="dot-badge on hiring-intent-badge">hiring intent</span>');else if(careers.length&&!badges.querySelector('.careers-badge'))badges.insertAdjacentHTML('beforeend','<span class="dot-badge on careers-badge">careers</span>')}) }
function spCareersEnhanceProfile(){let x=selectedCompany(),area=$('#hiring_and_public_activity');if(!x||!area||area.querySelector('.careers-boundary'))return;let careers=spCareersFacts(x),intent=spHiringIntentFacts(x),jobs=spJobFacts(x);if(!careers.length&&!intent.length&&!jobs.length)return;let first=careers[0],url=spCareersUrl(first),allFacts=[...careers,...intent,...jobs],evidence=uniqEvidence(allFacts.flatMap(f=>f.evidence||[]));let summary;if(jobs.length)summary=`Current evidence includes ${jobs.length} qualified specific job posting${jobs.length===1?'':'s'}.${intent.length?' Company-authored hiring intent is also published.':''}${careers.length?' A verified company-owned careers surface is also published.':''}`;else if(intent.length)summary=`Company-authored hiring intent is published from the exact first-party site, but no qualified specific job posting is published.${careers.length?' A verified careers surface is also published.':''}`;else summary='A verified company-owned careers surface is published, but it does not by itself establish company-authored hiring intent or a specific active vacancy.';let note=document.createElement('div');note.className='no-data careers-boundary';note.innerHTML=`<strong>Hiring evidence.</strong> ${summary}${url?` <a href="${esc(url)}" target="_blank" rel="noreferrer">Open careers page ↗</a>`:''}<div class="source-mini">${sourceButtons(evidence,'Hiring evidence')}</div>`;let head=area.querySelector('.area-head');head?.insertAdjacentElement('afterend',note);bindEvidenceButtons(note)}
const spCareersBaseRenderList=renderList;
renderList=function(){spCareersBaseRenderList();spCareersEnhanceList()};
const spCareersBaseRenderProfile=renderProfile;
renderProfile=function(){spCareersBaseRenderProfile();spCareersEnhanceProfile()};
const spCareersBaseAnswerQuestion=answerQuestion;
answerQuestion=function(q){let x=selectedCompany(),n=norm(q);if(x&&/(hiring|hire|job|jobs|vacanc|career)/.test(n)){let jobs=spJobFacts(x),intent=spHiringIntentFacts(x),careers=spCareersFacts(x);if(jobs.length)return {text:`Current evidence includes ${jobs.length} qualified specific job posting${jobs.length===1?'':'s'}.${intent.length?' Company-authored hiring intent is also published.':''}${careers.length?' A verified company-owned careers surface is also published.':''}`,evidence:uniqEvidence([...jobs,...intent,...careers].flatMap(f=>f.evidence||[]))};if(intent.length)return {text:`Company-authored hiring intent is published from the exact first-party site, but no qualified specific job posting is published.${careers.length?' A verified careers surface is also published.':''}`,evidence:uniqEvidence([...intent,...careers].flatMap(f=>f.evidence||[]))};if(careers.length)return {text:'A verified company-owned careers surface is published, but this alone does not establish company-authored hiring intent or a specific active vacancy.',evidence:uniqEvidence(careers.flatMap(f=>f.evidence||[]))};return {text:'No verified careers surface, company-authored hiring intent, or qualified specific job posting is published in the current evidence.',evidence:[]}}return spCareersBaseAnswerQuestion(q)};
function spCareersInstallAskSuggestion(){let box=$('#suggestions');if(!box||box.querySelector('[data-question="Are they hiring?"]'))return;let b=document.createElement('button');b.type='button';b.dataset.question='Are they hiring?';b.textContent='Hiring evidence';b.onclick=()=>{$('#askInput').value=b.dataset.question;renderAnswer(b.dataset.question)};box.appendChild(b)}
spCareersInstallFilter();
spCareersInstallAskSuggestion();
renderList();
renderProfile();
